# Generated by Django 5.2.7 on 2025-10-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'doctor', 'token_number']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
    ]
