# Generated by Django 5.2.7 on 2025-10-20 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('blood_test', 'Blood Test'), ('urine_test', 'Urine Test'), ('xray', 'X-Ray'), ('mri', 'MRI'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('ecg', 'ECG'), ('other', 'Other')], default='blood_test', max_length=50)),
                ('test_name', models.CharField(max_length=200)),
                ('report_file', models.FileField(upload_to='lab_reports/%Y/%m/%d/')),
                ('findings', models.TextField(blank=True, help_text='Key findings or summary')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for patient')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='hospital.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
